In [4]:
import numpy as np

# 1: np.array()

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

# 2: np.ones()

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

# 3: np.zeros()

In [4]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 4: np.random.rand()

In [7]:
np.random.rand(5,5)

array([[0.01127041, 0.05753042, 0.59201602, 0.57239326, 0.30227239],
       [0.09977554, 0.633468  , 0.52281204, 0.87513773, 0.53512612],
       [0.89710521, 0.49979001, 0.74648408, 0.71280692, 0.28658045],
       [0.63949639, 0.15532856, 0.31212518, 0.16251619, 0.06753531],
       [0.00909598, 0.18833711, 0.26751744, 0.85497206, 0.43280013]])

# 5: np.arange()

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# 6: np.split()

In [8]:
x=np.arange(1,10)
np.split(x,[2,3])

[array([1, 2]), array([3]), array([4, 5, 6, 7, 8, 9])]

# 7: np.reshape()

In [9]:
x=np.arange(1,10)
np.reshape(x,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 8: np.where()

In [12]:
x=np.arange(1,10)
x=np.where(x%2==0,-1,x)
x

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])

# 9: transpose()

In [15]:
x=np.arange(1,13)
x=np.reshape(x,(4,3))
x=x.transpose()
x

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

# 10: np.ravel()

In [17]:
x=np.arange(1,13)
x=np.reshape(x,(4,3))
x=np.ravel(x)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 11: np.mean()

In [18]:
x=np.arange(3,15)
x=np.mean(x)
x

8.5

# 12: np.sqrt()

In [20]:
x=np.arange(3,15)
np.sqrt(x)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739])

# 13: np.square()

In [21]:
x=np.arange(3,15)
np.square(x)

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196],
      dtype=int32)

# 14: np.percentile()

In [22]:
arr=np.arange(4,16)
np.percentile(arr,5)

4.55

# 15: np.median()

In [23]:
arr=np.arange(4,16)
np.median(arr)

9.5

# 16: np.ndim()

In [26]:
np.ndim(arr)

1

# 17: ndarray.shape

In [28]:
x=np.arange(1,13)
x=np.reshape(x,(4,3))
x.shape

(4, 3)

# 18: ndarray.dtype

In [29]:
x=np.arange(1,13)
x.dtype

dtype('int32')

# 19: ndarray.size

In [30]:
x=np.arange(1,13)
x.size

12

# 20: np.concatenate()

In [36]:
x=np.arange(1,13)
x=np.reshape(x,(4,3))
y=np.arange(13,25)
y=np.reshape(y,(4,3))
np.concatenate((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

# 21: np.hstack()

In [40]:
x=np.arange(1,13)
x=np.reshape(x,(4,3))
y=np.arange(13,25)
y=np.reshape(y,(4,3))
np.hstack((x,y))

array([[ 1,  2,  3, 13, 14, 15],
       [ 4,  5,  6, 16, 17, 18],
       [ 7,  8,  9, 19, 20, 21],
       [10, 11, 12, 22, 23, 24]])

# 22: np.empty()

In [49]:
x=np.empty((2,3))
x

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313]])

# 23: np.intersect1d()

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

# 24: ndarray.min()

In [45]:
 
x = np.array([7,2,10,2,7,4,9,4,9,8])
x.min()

2

# 25: ndarray.max()

In [46]:
a = np.array([1,25,32,24,3,74,3,4,15,6]) 
a.max()

74

# 26: np.identity()

In [50]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 27: np.multiply()

In [51]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])


arr3=np.multiply(arr1,arr2)
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# 28: np.flip()

In [52]:
arr=np.arange(1,12)
np.flip(arr)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# 27: np.dot()

In [54]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

# 28: np.std()

In [55]:
x=np.arange(1,18)
np.std(x)

4.898979485566356

# 29: np.any()

In [59]:
x=[True,False,False]
np.array(x)
np.any(x)

True

# 30: np.all()

In [61]:
x=[False,False,False,True]
np.array(x)
np.all(x)

False

# 31: np.swapaxes()

In [62]:
arr3d=[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]
np.swapaxes(arr3d,2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

# 32: np.maximum()

In [63]:
arrA=np.random.rand(12)
arrB=np.random.randn(12)
arrC=np.maximum(arrA,arrB)
arrC

array([0.90713498, 0.60162517, 0.10113875, 0.95607327, 0.09603677,
       0.53630108, 0.95563011, 1.06670816, 2.41475963, 0.84902035,
       0.543047  , 0.79804991])

# 33: np.unique()

In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

# 34: np.sort()

In [65]:
x=[23,3,555,1,4,78,34,98,2,0,11,52]
np.sort(x)

array([  0,   1,   2,   3,   4,  11,  23,  34,  52,  78,  98, 555])

# 35: np.cumsum()

In [66]:
arr=np.random.rand(20)
np.cumsum(arr)

array([0.12186503, 0.24111466, 0.28759799, 0.9912413 , 1.87049508,
       2.57173041, 2.92529189, 2.97993859, 3.38409239, 3.93574344,
       4.26180701, 4.56036774, 4.80790246, 4.8132424 , 5.32983912,
       6.04335395, 6.22330155, 6.5892016 , 6.63236171, 7.4415938 ])