# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [9]:
y=np.arange(10,50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [11]:
np.shape(y)

(40,)

5. Print the type of the previous array in question 3

In [12]:
y.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [34]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ehsan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Ehsan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ehsan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [14]:
y.ndim

1

8. Create a boolean array with all the True values

In [30]:
boolArr=np.array([1,4,True,'a'],dtype=bool)


9. Create a two dimensional array




In [36]:
arr=np.array([[1,2,3,4],[5,6,7,9]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

10. Create a three dimensional array



In [38]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,1]]])
np.shape(arr)

(2, 2, 3)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [4]:
arr=np.arange(1,12)
np.flip(arr)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [46]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [39]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [40]:
arr=np.array([1,2,3,4,5],dtype='float')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [6]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])


arr3=np.multiply(arr1,arr2)
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [3]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3=arr1==arr2
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [10]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]



array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [8]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
np.where(arr%2==0,arr,-1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [17]:
arr=np.arange(10)
arr[5:9:1]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [11]:
arr=np.ones((4,4))
arr[1:3:1,1:3:1]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [24]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],  [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [30]:
arr=np.arange(0,10)
arr2=np.reshape(arr,(2,5))
arr2[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [31]:
arr=np.arange(0,10)
arr2=np.reshape(arr,(2,5))
arr2[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [40]:
arr=np.arange(0,9)
arr2=np.reshape(arr,(3,3))
arr2[0:2,2:3]



array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
x=np.random.randn(10,10)
x.min()
x.max()

3.2266174821963616

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)


(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [19]:
data = np.random.randn(7, 4)
data
x= np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
x

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [26]:
arr2D=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [1]:
arr3d=[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]


33. Swap axes of the array you created in Question 32

In [10]:
np.swapaxes(arr3d,2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [22]:
x=np.random.rand(10)
xSqrt=np.sqrt(x)
xSqrt=np.where(xSqrt<0.5,0,xSqrt)
xSqrt


array([0.        , 0.55465534, 0.70161467, 0.64763853, 0.55125234,
       0.5982769 , 0.96234757, 0.74576253, 0.        , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [25]:
arrA=np.random.rand(12)
arrB=np.random.randn(12)
arrC=np.maximum(arrA,arrB)
arrC

array([0.79419835, 1.00518347, 0.30108622, 0.60763005, 0.6085914 ,
       0.09374512, 1.05768725, 0.35075373, 1.56800436, 0.86510266,
       0.68022773, 0.86637766])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names2=np.unique(names)
names2.sort()
names2

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [36]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c=[a==b]
c

[array([False, False, False, False, False])]

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [8]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
newColumn = numpy.reshape(newColumn ,(3,1))
sampleArray=numpy.split(sampleArray,[2],axis=1)
sampleArray = numpy.concatenate((sampleArray,newColumn))

sampleArray



ValueError: could not broadcast input array from shape (3,2) into shape (3)

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [14]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [19]:
arr=np.random.rand(20)
np.cumsum(arr)

array([0.28797258, 0.30461875, 0.45769079, 0.94310712, 1.78579355,
       2.56822723, 2.82767264, 3.54963514, 4.02893559, 4.95480778,
       5.09755789, 5.47366082, 5.62953349, 5.65547035, 6.13085139,
       6.76972952, 7.50374514, 8.2279678 , 8.54780312, 9.23229773])